### PR TITLE
Support only_upgrade

### LINKED ISSUE #3629: package-latest fails for apt if only_upgrade is used
##### Summary

currently the check for package-latest fails as the `apt` module provided the parameter `only_upgrade` to `Only upgrade a package if it is already installed.` and not `update_only` as currently coded in the check:

https://github.com/ansible/ansible-lint/blob/b1e8a5f95ba1ecbc9e4705f2c5e403cc818bf339/src/ansiblelint/rules/package_latest.py#L79-L82

The `only_upgrade` parameter is documented at https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-only_upgrade

Please align the check for the `apt` module and check if the other package manager supports this option also (as it's not listed in the documentation for [pip](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html#parameters)).

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
$ ansible-lint --version
ansible-lint 6.17.2 using ansible-core:2.15.1 ansible-compat:4.1.5 ruamel-yaml:0.17.32 ruamel-yaml-clib:0.2.7
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

```console (paste below)
$ cat bug.yml 
---
- name: Initial OS setup
  hosts: localhost
  become: true
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        only_upgrade: true
...

$ ansible-lint bug.yml 
WARNING  Skipped installing old role dependencies due to running in offline mode.
WARNING  Skipped installing collection dependencies due to running in offline mode.
WARNING  Listing 1 violation(s) that are fatal
package-latest: Package installs should not use latest.
bug.yml:6 Task/Handler: Update all packages to their latest version

Read documentation for instructions on how to ignore specific rule violations.

              Rule Violation Summary               
 count tag            profile rule associated tags 
     1 package-latest safety  idempotency          

Failed: 1 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'moderate'. Rating: 2/5 star
```

##### Desired Behavior

```
Passed: 0 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'production'.
```

##### Actual Behavior
```paste below
package-latest: Package installs should not use latest.
bug.yml:6 Task/Handler: Update all packages to their latest version

Read documentation for instructions on how to ignore specific rule violations.

              Rule Violation Summary               
 count tag            profile rule associated tags 
     1 package-latest safety  idempotency          

Failed: 1 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'moderate'. Rating: 2/5 star
```

### PR DESCRIPTION
**Pull request by soroshsabz**
Fixes: #3629

### CODE REVIEW

**Comment by soroshsabz** [comment]
@ajinkyau please add bug label for this PR and review it

thanks

**Review by ssbarnea — CHANGES_REQUESTED** [review]
I think that you need to update the test that fails to make it look for 5 errors instead of 4, other than this this fix looks just fine to me.

I tried to push the fix myself but I was not allowed because you used your main branch.

**Comment by soroshsabz** [comment]
@ssbarnea I resolve your note

please review again

thanks

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
