### PR TITLE
Add rule to check key order

### PR DESCRIPTION
**Pull request by jeefberkey**
Adds a new rule that for the moment checks that name is the first key on tasks. In the future
we will add additional ordering rules to it.

Partial: https://github.com/ansible/ansible-lint/issues/578

### CODE REVIEW

**Comment by ssbarnea** [comment]
@jeefberkey Please update PYTEST_REQPASS and increase its value to match expected number of tests (+2).

**Comment by jeefberkey** [comment]
Thanks for the additional guidance - `rg` was ignoring the directory when I was looking for that number.

**Comment by ssbarnea** [comment]
> Thanks for the additional guidance - `rg` was ignoring the directory when I was looking for that number.

I am an rg user myself, great tool! I have an alias `rg='rg --hidden --no-follow --max-columns 255 --no-heading --column -F'` that you might like.

**Comment by ssbarnea** [comment]
@jeefberkey I pushed some minor changes, like removing opt-int, we will make it experimental from start as it is very useful.

**Review by ssbarnea — APPROVED** [review]

**Comment by jeefberkey** [comment]
Thanks for the test fixes, I was working on them but was sick the past few days. The new test name may conflict with other things I'm working on, but we can deal with that later

**Review by cidrblock — APPROVED** [review]
love it.

**Comment by ssbarnea** [comment]
> Thanks for the test fixes, I was working on them but was sick the past few days. The new test name may conflict with other things I'm working on, but we can deal with that later

Please mention more details about conflicts we might have? While class name is not important, the `id` of the rule is harder to change once we merge it, so better to get it right from start. I used `key-order` because I want to evolve this rule to take care of ordering of keys in general.

**Review by cognifloyd — APPROVED** [review]

**Comment by jeefberkey** [comment]
Nothing, this is actually not a blocker now that I think about it.

**Pull request merged**
