### PR TITLE
Add Package has retry rule

### PR DESCRIPTION
**Pull request by hughsaunders**
Apt operations are unreliable as they involve network access and
remote servers. To mitigate potential failures, retries should be used.

### CODE REVIEW

**Comment by evrardjp** [comment]
I welcome this change.

**Comment by evrardjp** [comment]
I agree this should test the package action plugin, instead of the apt module.

**Comment by hughsaunders** [comment]
Extended to all the package modules, excluding a few that appear to be  local only (eg dpkg, and apt_repository).

**Comment by evrardjp** [comment]
Probably worth renaming the PR, and making sure it passes tests :)

**Comment by hughsaunders** [comment]
Failed job ran for 9 hours, with log output "null" https://api.travis-ci.org/v3/job/341984987/log.txt

**Comment by hughsaunders** [comment]
Closed and re-opened to retry tests.

**Comment by evrardjp** [comment]
up?

**Comment by gundalow** [comment]
Closing and re-opening to trigger CI.

**Comment by awcrosby** [comment]
My refactoring of this PR pushed a long commit history, apologies for that, so I have incorporated and merged the refactored edits in #400 - thanks for the contribution!

Refactored edits:
- Changed id and tags
- Re-ran and sorted generated module list
- Refactored test case to be in one file

**Pull request closed without merging**
