### PR TITLE
Avoid "unable to evaluate string as dictionary" with args rule

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes: #3128

### CODE REVIEW

**Comment by Et7f3** [comment]
Do you prefer this test ?

```
---
- hosts: all
  name: Something
  connection: local
  vars:
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN
  check_mode: true
  tasks:
    - name: Set tcp flags
      ansible.builtin.iptables:
        chain: OUTPUT
        jump: DROP
        protocol: tcp
        tcp_flags: "{{ tcp_flags }}"
```

Do you want a PR to add it somewhere ?

**Comment by ssbarnea** [comment]
@Et7f3 I tried this one too, no errors with code from main branch, reported all green.

**Comment by Et7f3** [comment]
I reproduced with

```
ansible-lint 6.14.1 using ansible 2.14.3
```

(and reverting this PR)

I can send you a nix expression so you can fully reproduce my setup ? Or you prefer other way to reproduce (nix is better IMO) ?

**Comment by Et7f3** [comment]
Here is a reproduction:

```let
  nixpkgs = builtins.fetchTarball {
    url = "https://github.com/Et7f3/nixpkgs/archive/repro_bug_ansible_lint.tar.gz";
  };
in
{...}@args: with import nixpkgs args; (pkgs.runCommandCC or pkgs.runCommand) "shell" {
  buildInputs = with pkgs; [
    #ansible
    git
    ansible
    ansible-lint
  ];
  shellHook = ''
    # nix on ubuntu
    export LANG=en_US.UTF-8
    if test -f /usr/lib/locale/locale-archive
    then
      export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive
    fi
  '';
} "
mkdir -p failure
cd failure
git init .
ansible-lint --version
cat > playbook.yml <<EOF
---
- hosts: all
  name: Something
  connection: local
  vars:
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN
  check_mode: true
  tasks:
    - name: Set tcp flags
      ansible.builtin.iptables:
        chain: OUTPUT
        jump: DROP
        protocol: tcp
        tcp_flags: \"{{ tcp_flags }}\"
EOF
ansible-lint playbook.yml"
```

put this in a shell.nix and `nix-shell --pure shell.nix` (the pure is optional but isolate better) You can call `sh $buildCommandPath`

**Comment by Et7f3** [comment]
The error evolved 
image

**Pull request merged**
