### PR TITLE
UsingBareVariablesIsDeprecatedRule supports multiline templates

### PR DESCRIPTION
**Pull request by gzm55**
should fix issue #250

### CODE REVIEW

**Comment by gundalow** [comment]
@willthames What are you thoughts on this?

**Comment by gzm55** [comment]
@willthames @gundalow 
fix the conflicts. is there anyone have time to review this pr?

**Comment by tux21b** [comment]
Please merge, we are hitting the same bug (issue #250) after updating to ansible-lint 4.1 and there seems to be currently no way to make the linter happy:

If we avoid newlines, we will trigger the maximum line length check and if we do not, we will trigger this check because it does not support newlines.

**Comment by awcrosby** [comment]
We'll plan on getting this in the next release

**Pull request merged**
