### PR TITLE
Rule 405 now ignore case of 'yum: list=package'

### PR DESCRIPTION
**Pull request by zigarn**
https://docs.ansible.com/ansible/latest/modules/yum_module.html
`list` is for retrieving available packages, not sure it needs the `until` loop.

### CODE REVIEW

**Comment by awcrosby** [comment]
I think this is a reasonable addition. @zigarn can you [signoff](https://github.com/ansible/ansible-lint/pull/444/checks?check_run_id=43248243) your commit?

**Comment by zigarn** [comment]
Signed-off

**Comment by alfredopalhares** [comment]
This rule is not on `405`, is not yet on https://docs.ansible.com/ansible-lint/rules/default_rules.html

**Comment by zigarn** [comment]
> This rule is not on `405`, is not yet on https://docs.ansible.com/ansible-lint/rules/default_rules.html

@alfredopalhares: Is not _anymore_: #465

**Pull request merged**
