### PR TITLE
Clean up link handling logic

### PR DESCRIPTION
**Pull request by davedittrich**
This change cleans up the logic surrounding handling linked directories.

I was getting confusing exceptions when running `molecule` (which in turn runs `ansible-lint`) because `ansible-compat` created a directory, not a link. This more clearly expresses the logical flow of this section of code and hopefully makes it easier for others to debug similar indirect exceptions raised during `molecule` runs.

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
I did not check why the jobs failed but I can see a clear regression, new code is not able to repair an existing symlink that is either broken or pointing to a wrong location. We also want to avoid changing things unless needed. Be aware that python can behave unexpected when it comes to performing exist tests on symlinks.

If you want to fix a bug on this area, how about just adding a test that reproduce the bug? I could do the fix if I have the test.

**Comment by heindsight** [comment]
@davedittrich the error you describe sounds like the same issue that was reported in #2265. I created [heindsight/ansible-lint-vs-molecule](https://github.com/heindsight/ansible-lint-vs-molecule) as a demonstration/reproducer of that bug.

@ssbarnea I've taken a stab at writing a test to reproduce this here: https://github.com/ansible/ansible-lint/compare/main...heindsight:ansible-lint:cache-link-conflict

**Comment by davedittrich** [comment]
I just saw [this fix](https://github.com/ansible/ansible-lint/pull/2466#issuecomment-1255208471) and had a deja-vu ("I've seen that code somewhere before!"). It resonates with [this comment](https://github.com/ansible/ansible-lint/issues/2426#issuecomment-1251588548) and might apply here as well..

I think the issue is a combination of non-DRY coding (same code, different places) combined with the logic issue I raised, which is use of `try`/`except`/`pass` instead of clear `if`/`else` logic.

What do y'all think?

P.S. I actually was using a much simpler (but similar) mechanism of symbolic links, but I was explicit about adding another path to `ANSIBLE_COLLECTIONS_PATH`. It is [described here](https://github.com/davedittrich/utils#testing). My method was working fine over a year ago, but broke horribly when I updated all the components to start working on it again. I had to significantly change my code to use modern `molecule` and keep my code (which used `testinfra`) but the symbolic link bug related to the code in this PR had me spinning my wheels for days.

**Comment by ssbarnea** [comment]
This was already fixed on main branch.

**Pull request closed without merging**
