### PR TITLE
Update schemas

### PR DESCRIPTION
**Pull request by jeefberkey**
Update schemas for #2222

### CODE REVIEW

**Comment by ssbarnea** [comment]
You will need to include the changes made to eco projects output to make it pass.

**Comment by jeefberkey** [comment]
I'm not sure that debops cleaned up _all_ of their lint errors but it looks like it... https://github.com/debops/debops/commit/065a412eebe7718d11a1d3695c5e08e74fa8e059

I would like someone else's opinion, to make sure.

**Comment by ssbarnea** [comment]
@jeefberkey Yes, they did, even pinged me on matrix to report the success.

**Comment by jeefberkey** [comment]
@ssbarnea I'm having a hard time reproducing this error locally, would you mind taking a look?

**Comment by ssbarnea** [comment]
Have you run "tox -e exo" locally? it should update some files. Once you include them with the change it should pass.

**Comment by jeefberkey** [comment]
Sorry, that first question was not helpful. Here's what I'm working with:

```
ansible-lint on 🌱 update-schema [!?] via 🐍 v3.10.5 took 2m40s 
✗ tox -e eco --allow-dirty
eco installed: ansible-compat==2.1.0,ansible-core==2.13.0,-e git+ssh://git@github.com/jeefberkey/ansible-lint.git@773df30b323542f0468b68e2c121f88c2f343ab4#egg=ansible_lint,astroid==2.11.5,attrs==21.4.0,black==22.3.0,bracex==2.3.post1,cffi==1.15.0,click==8.1.3,commonmark==0.9.1,coverage==6.4.1,cryptography==37.0.2,dill==0.3.5.1,enrich==1.2.7,execnet==1.9.0,flake8==4.0.1,flaky==3.7.0,iniconfig==1.1.1,isort==5.10.1,Jinja2==3.1.2,jsonschema==4.6.0,lazy-object-proxy==1.7.1,MarkupSafe==2.1.1,mccabe==0.6.1,more-itertools==8.13.0,mypy==0.960,mypy-extensions==0.4.3,packaging==21.3,pathspec==0.9.0,platformdirs==2.5.2,pluggy==1.0.0,psutil==5.9.1,py==1.11.0,pycodestyle==2.8.0,pycparser==2.21,pyflakes==2.4.0,Pygments==2.12.0,pylint==2.14.0,pyparsing==3.0.9,pyrsistent==0.18.1,pytest==7.1.2,pytest-cov==3.0.0,pytest-forked==1.4.0,pytest-plus==0.2,pytest-xdist==2.5.0,PyYAML==6.0,resolvelib==0.5.4,rich==12.4.4,ruamel.yaml==0.17.21,ruamel.yaml.clib==0.2.6,subprocess-tee==0.3.5,tomli==2.0.1,tomlkit==0.11.0,typing_extensions==4.2.0,wcmatch==8.4,wrapt==1.14.1,yamllint==1.26.3
eco run-test-pre: PYTHONHASHSEED='2261128188'
eco run-test: commands[0] | pytest -n auto -m eco
============================================== test session starts ==============================================
platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
cachedir: .tox/eco/.pytest_cache
rootdir: /home/nick/src/ansible-lint, configfile: pytest.ini
plugins: flaky-3.7.0, plus-0.2, forked-1.4.0, xdist-2.5.0
gw0 [9] / gw1 [9] / gw2 [9] / gw3 [9] / gw4 [9] / gw5 [9] / gw6 [9] / gw7 [9]
.........                                                                                                 [100%]
========================================= 9 passed in 154.69s (0:02:34) =========================================
____________________________________________________ summary ____________________________________________________
  eco: commands succeeded
  congratulations :)

ansible-lint on 🌱 update-schema [?] via 🐍 v3.10.5 took 2m37s 
❯ git status
On branch update-schema
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.editorconfig

nothing added to commit but untracked files present (use "git add" to track)

ansible-lint on 🌱 update-schema [?] via 🐍 v3.10.5 took 854ms 
❯ 
```

**Comment by apatard** [comment]
any news on this schemas update ? still stuck with the eco test error, right ?

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
