### PR TITLE
Allow warnings to be skipped

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes: #2868
Closes: #2917

### CODE REVIEW

**Review by cidrblock — APPROVED** [review]

**Comment by nkakouros** [comment]
@ssbarnea I don't think this is the right fix. What this PR does is not output the error about the empty-playbook if the rule is excluded. Still, `warning[emtpy-playbook]` remains fatal and no further checks are done, which should not be the case given that an empty playbook really is not fatal. For example, given the files below:

```
# vars/main.yml
q: 1
```

```
# playbooks/main.yml
---
```

if I run `ansible-lint -x 'warning[empty-playbook]' vars playbooks`, I get:

```

Passed with production profile: 0 failure(s), 0 warning(s) on 6 files.
You are using a pre-release version of ansible-lint.
```

`ansible-lint` never reaches the point where it checks that vars file (to complain about a missing doc start).

And there is also the question if a `warning` should be considered as `fatal error` by default (I argue it should not).

**Comment by ssbarnea** [comment]
You are confusing the special rune named "warning" with the warning level. They are two different things, and the warning meta-rule can act as a warning or error (levels).

**Comment by nkakouros** [comment]
There are 3 issues here and I think you would agree that there is sth at least inconsistent if not wrong. It would be great to hear your view on these 3 points.

1. It is not me that confuses the two. The [docs](https://ansible-lint.readthedocs.io/rules/warning/) say:

> warning is a special type of internal rule that is used to report generic runtime warnings found during execution. As stated by its name, they are not counted as errors, so they do not influence the final outcome.

So, `warning` rules are about warnings according to the docs

2. Regardless of naming, do you think it is fine for this rule to be fatal and stop execution of further rules? 

`warning[empty-playbook]` breaks further execution because it relies on ansible-playbook's `--syntax-check` behavior where an empty playbook is fatal. But even ansible-playbook can run an empty playbook without issue (`ansible-playbook path/to/empty/playbook` works fine and further playbooks in the command line are run without issue).

There is nothing really other than the above that prevents `ansible-lint` from continuing to check files, there is no for example bad yaml where ansible-lint will not know how to parse it. This is apparent in [my PR](https://github.com/ansible/ansible-lint/pull/2917) where I modified the code to not follow `ansible-playbook --check` by making that warning non-breaking, but still reporting it.

3. Especially with this PR here, if the user skips `warning[empty-playbook]`, they may see:

```
Passed with production profile: 0 failure(s), 0 warning(s) on 6 files.
```

which is misleading. Ansible-lint has not actually checked 6 files and found them ok, it just stopped after the empty playbook and did not applied most of the rest of the rules.

**Comment by ssbarnea** [comment]
Please create a new issue for this and we can work next week to address it. It might need multiple changes but that is not a problem, we should fix it and probably do it will also involve avoiding using "warning" as a rule name.

**Comment by nkakouros** [comment]
I opened #2927.

**Pull request merged**
