### PR TITLE
Remove azure-pipelines integration

### PR DESCRIPTION
**Pull request by ssbarnea**
Removes Azure Pipelines CI/CD integration as the entire testing matrix
is already already fully covered by GitHub Actions.

Partial: #823

### CODE REVIEW

**Comment by ssbarnea** [comment]
> I don't like getting rid of useful features not present elsewhere like, well-visualized test run/cov reports.

I think that the added complexity of having azure-pipelines enabled heights more than the perceived benefits of nice reporting. We should remember that these gimmicks can be implemented on the other two, zuul or github actions. I know for sure that passing coverage results between jobs and combining them and publishing  is possible with zuul (just that nobody bothered to implement them).

We can think from another perspective: how many bugs did the consolidated coverage report prevented us from introducing in the last year? The CI/CD role is to prevent bugs, not to generate nice reports.

Lets see what other think about it. IMHO, is better to invest more effort in better maintaining a lower number of CI/CD systems.

There are also two aspects we forgot to consider:
* we could consider dropping github-workflows instead of azure-pipelines if the reports are so important
* costs: how do our decisions impact CI/CD costs and how does this play with Ansible plans regarding CI/CD testing in general (like increasing investing in
one or reducing investing in another one). If we are on free tiers on both, that is less important.

**Comment by webknjaz** [comment]
@ssbarnea suggesting zuul is unreasonable because its UI is the worst and you know it. As for the CI costs, all current CIs are on respective free plans. They are all already well-configured and need next to zero maintenance.

**Comment by albinvass** [comment]
> @ssbarnea suggesting zuul is unreasonable because its UI is the worst and you know it. As for the CI costs, all current CIs are on respective free plans. They are all already well-configured and need next to zero maintenance.

Can we please try to have a serious discussion about issues?
Saying things like '...its UI is the worst and you know it.' is not constructive in any way and does not add to the conversation.

Can you please try to describe what problems you are experiencing instead, and how other systems are more user friendly?

**Comment by webknjaz** [comment]
Sorry, I don't have the energy for this right now.

**Comment by awcrosby** [comment]
since the tests are covered by GitHub Actions, I support reducing the complexity of the CI

**Comment by webknjaz** [comment]
Honestly, I'd also drop travis but that would require some help from @gundalow (because we'd need new secrets).

**Comment by gundalow** [comment]
If this part (dropping AZ pipelines) is good, could we please merge. Then as a follow up we can review Travis?

Let's be mindful not to try and solve all problems at once.

**Pull request merged**
