### PR TITLE
Handle argv syntax for the command module

### PR DESCRIPTION
**Pull request by maxwell-k**
Addresses issues raised at <https://github.com/ansible/ansible-lint/issues/352> and <https://github.com/ansible/ansible-lint/issues/391>

First attempt at addressing this issue, happy to action any feedback.

### CODE REVIEW

**Comment by willthames** [comment]
@maxwell-k Can you add a few test cases into the test suite for this change please

**Comment by webknjaz** [comment]
@maxwell-k?

**Comment by maxwell-k** [comment]
I will add some tests, I can't say when I will have time to write them. To recap the timeline for this feature:

2018/06/28: Ansible 2.6 released supporting new ARGV syntax
2018/07/11: #352 reported, the next day Will replies letting me know it is low priority
2018/12/11: this PR proposed, the next day Will asks me to add tests

If RedHat or any of the Ansible core team have capacity to add support for this more quickly, then great. 

@webknjaz What is your question? Does this comment answer it?

**Comment by awcrosby** [comment]
@maxwell-k I added tests as part of an existing rule test. I think this can go into 4.1.0
Thanks for reporting this and your contribution!
Fixes: #352

**Pull request merged**
