### PR TITLE
Make SARIF output specification compliant

### PR DESCRIPTION
**Pull request by atiterlea**
The implementation uses the (unique) tag value instead of the rule ID.

Fixes: #2667

### CODE REVIEW

**Comment by atiterlea** [comment]
This failed test doesn't appear to have been introduced by my changes as it's failing in other PRs and on the mainline branch as well:

```
=================================== FAILURES ===================================
______________ test_template_lookup[template_lookup_missing-True] ______________
[gw0] linux -- Python 3.8.14 /home/runner/work/ansible-lint/ansible-lint/.tox/py38/bin/python

role = 'template_lookup_missing', expect_warning = True

    @pytest.mark.parametrize(
        ("role", "expect_warning"),
        (
            ("template_lookup", False),
            # With 2.15 ansible replaced the runtime Warning about inability to
            # open a file in file lookup with a full error.
            ("template_lookup_missing", runtime.version_in_range(upper="2.14")),
        ),
    )
    def test_template_lookup(role: str, expect_warning: bool) -> None:
        """Assure lookup plugins used in templates does not trigger Ansible warnings."""
        task_path = os.path.realpath(
            os.path.join(
                os.path.dirname(os.path.realpath(__file__)),
                "..",
                "examples",
                "roles",
                role,
                "tasks",
                "main.yml",
            )
        )
        result = run_ansible_lint("-v", task_path)
>       assert ("Unable to find" in result.stderr) == expect_warning
E       assert ('Unable to find' in 'WARNING  Collection install skipped because ansible versions before 2.14 do not support an offline mode.\nINFO     Se...  1 name[missing]  basic   idiom                \n\nFailed after min profile: 3 failure(s), 0 warning(s) on 1 files.\n') == True
E        +  where 'WARNING  Collection install skipped because ansible versions before 2.14 do not support an offline mode.\nINFO     Se...  1 name[missing]  basic   idiom                \n\nFailed after min profile: 3 failure(s), 0 warning(s) on 1 files.\n' = CompletedProcess(args=['/home/runner/work/ansible-lint/ansible-lint/.tox/py38/bin/python', '-m', 'ansiblelint', '--off... 1 name[missing]  basic   idiom                \n\nFailed after min profile: 3 failure(s), 0 warning(s) on 1 files.\n").stderr

expect_warning = True
result     = CompletedProcess(args=['/home/runner/work/ansible-lint/ansible-lint/.tox/py38/bin/python', '-m', 'ansiblelint', '--off... 1 name[missing]  basic   idiom                \n\nFailed after min profile: 3 failure(s), 0 warning(s) on 1 files.\n")
role       = 'template_lookup_missing'
task_path  = '/home/runner/work/ansible-lint/ansible-lint/examples/roles/template_lookup_missing/tasks/main.yml'

test/test_utils.py:2[76](https://github.com/ansible/ansible-lint/actions/runs/3418307509/jobs/5690444320#step:11:77): AssertionError
```

**Comment by ssbarnea** [comment]
You are right. Someone needs to fix that test before we can merge the other PRs. I am currently in vacation for another week so I am not sure if I will find time to do it myself.

**Review by aalsabag — APPROVED** [review]

**Comment by atiterlea** [comment]
The test that's failing in the `py39 (wsl)` check looks like it's tied to some dependency mismatch between the INI module offered in Linux distros and the module loaded into a Windows filesystem. Is it possible that the module just isn't loaded on WSL, or not found in its expected location?

**Comment by mitchell-liatrio** [comment]
Hi @ssbarnea, will this fix be published soon?

**Pull request merged**
