### PR TITLE
Add initial handling of submodules to contribution docs

### PR DESCRIPTION
**Pull request by klaus-tux**
Fixes: #3351

I submitted my last PR to ansible-lint before the submodule was introduced. If this was mentioned in the documentation it would have saved a lot of time for me.

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Better than adding extra commands is to add `--recursive` to git clone one.

**Comment by klaus-tux** [comment]
The man page does not document `--recursive` but `--recurse-submodules`. I prefer the latter, because it makes more explicit that submodules are used. Drop me a comment if you prefer `--recursive` nevertheless.

**Comment by ssbarnea** [comment]
Please use recursive, as we might drop the submodule in the future and we would not need to update the docs anymore.

**Comment by ssbarnea** [comment]
BTW, thanks for contributing, even minor changes like this can help others.

**Comment by klaus-tux** [comment]
Changed as requested :-)

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
